### ISSUE TITLE
word_ngram result doesn't seem right

### ISSUE THREAD

**Issue by yushanyong** [jctian98/e2e_lfmmi#1]
Hi, I tried running `nets/scorers/word_ngram.py`, but the result doesn't seem to be as expected

```
if __name__ == "__main__":
    device = torch.device("cuda:0")
    lang = sys.argv[1]
    word_ngram = WordNgram(lang, device)

    texts = ["甚至出现交易停滞的情况", "甚至出现交易停滞的情形", "欲擒故纵", "欲擒故放"]
    for i in range(1):
        scores = word_ngram.score_texts(texts, log_semiring=True)
        print(scores)
```
result
```
tensor([-inf, -inf, -inf, -inf], device='cuda:0', dtype=torch.float64)
```

G.fst.txt: 
```
ngram-count -order 3 -lm aishell.arpa -kndiscount -interpolate -text text

python3 -m kaldilm \
  --read-symbol-table="words.txt" \
  --disambig-symbol='#0' \
  --max-order=3 \
  aishell.arpa > G.fst.txt
```
The `words.txt` file has 137079 lines, and nothing abnormal was found.

thanks.

**Comment by jctian98** [comment]
We have also encountered this problem before. A simple workaround is to run this script for twice. 

When you run this script without the `G.pt`, it will build a new one and save it to disk. However, all results would be `-inf`.
The second time you run this script with the `G.pt`, it will work as expected. So far we don't know why this happens.

regards.
