### ISSUE TITLE
aishell1 is incompletely executed

### ISSUE THREAD

**Issue by kaiAksenov** [jctian98/e2e_lfmmi#12]
Hello, please ask the following this contains all the code related to e2e lfmmi, which feels missing when executing (e.g., lfmmi criterion)

**Comment by jctian98** [comment]
Hi. All the code is released in this repo. The LFMMI criterion is here: https://github.com/jctian98/e2e_lfmmi/blob/master/snowfall/warpper/warpper_mmi.py
Please tell me if you feel other things are missing.

**Comment by kaiAksenov** [comment]
> Hi. All the code is released in this repo. The LFMMI criterion is here: https://github.com/jctian98/e2e_lfmmi/blob/master/snowfall/warpper/warpper_mmi.py Please tell me if you feel other things are missing.

For example, you have specified relevant parameters in the nt.sh script, but asr_train.py has no corresponding parameter identifiers
![a4f740cb6b1805099c76bc270cabec3](https://user-images.githubusercontent.com/95283469/185788414-0f5d5e39-e897-4683-b43a-9e89529c4176.png)

asr_train.py: error: unrecognized arguments: --aux-ctc true --aux-ctc-weight 0.5 --aux-ctc-dropout-rate 0.1 --aux-mmi true --aux-mmi-weight 0.5 --aux-mmi-dropout-rate 0.1 --aux-mmi-type mmi --att-scorer-weight 0.0

In addition, args.use_ddp is used in asr.py called by asr_train.py, but the relevant configuration is not specified accordingly

**Comment by jctian98** [comment]
Hi, these arguments are defined here. Maybe we need to check this function is called correctly so these arguments are registered in the argument parser.
https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/nets/pytorch_backend/transducer/arguments.py#L320-L345

DDP is the only way to run this repo even if only one GPU is used. I'm sorry I didn't remove this option.

**Comment by kaiAksenov** [comment]
> Hi, these arguments are defined here. Maybe we need to check this function is called correctly so these arguments are registered in the argument parser.
> 
> https://github.com/jctian98/e2e_lfmmi/blob/34b8056906631c6282bd2f0320764d645c33ca0d/nets/pytorch_backend/transducer/arguments.py#L320-L345
> 
> DDP is the only way to run this repo even if only one GPU is used. I'm sorry I didn't remove this option.

Oh,thanks，but how should I use arguments.py to add these parameters?
Also, I feel that the return of args is unreasonable, and the corresponding single parameter cannot be obtained，
Can you update the code a little bit, the nt.sh pipeline is not running smoothly？
![36132979978417b47808e0b458a5cd2](https://user-images.githubusercontent.com/95283469/185795683-4d38fb81-a84e-4702-ba4d-114e6984a4b0.png)
![Uploading db87aec3fbd1ad14ecd106cd9e2d509.png…]()
![Uploading c6c961bec976ebce27a039dbec6522b.png…]()
