### ISSUE TITLE
env question

### ISSUE THREAD

**Issue by casper-110368104** [jctian98/e2e_lfmmi#15]
I followed the instructions, but there is always a version conflict. How can I improve it?

[root@b394acbc6baf tools]# make TH_VERSION=1.7.1 CUDA_VERSION=10.1 
CUDA_VERSION=10.1
PYTHON=/anaconda/envs/lfmmi/bin/python3
PYTHON_VERSION=Python 3.9.15
USE_CONDA=1
TH_VERSION=1.7.1
WITH_OMP=ON
. ./activate_python.sh && ./installers/install_torch.sh "true" "1.7.1" "10.1"
2022-12-07T05:51:42 (install_torch.sh:149:main) [INFO] python_version=3.9.15
2022-12-07T05:51:42 (install_torch.sh:150:main) [INFO] torch_version=1.7.1
2022-12-07T05:51:42 (install_torch.sh:151:main) [INFO] cuda_version=10.1
2022-12-07T05:51:43 (install_torch.sh:97:install_torch) conda install -y pytorch=1.7.1 torchaudio=0.7.2 cudatoolkit=10.1 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package pytorch conflicts for:
torchaudio=0.7.2 -> pytorch==1.7.1
pytorch=1.7.1

Package _openmp_mutex conflicts for:
pytorch=1.7.1 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
python=3.9 -> libgcc-ng[version='>=11.2.0'] -> _openmp_mutex[version='>=4.5']

Package cudatoolkit conflicts for:
torchaudio=0.7.2 -> pytorch==1.7.1 -> cudatoolkit[version='>=10.1,<10.2|>=11.0,<11.1|>=10.2,<10.3|>=9.2,<9.3']
cudatoolkit=10.1The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - python=3.9 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

make: *** [Makefile:102: pytorch.done] Error 1

**Comment by baixf-xyz** [comment]
I think maybe your python version is high,the author use python which version is 3.8
ref:https://github.com/jctian98/e2e_lfmmi/blob/master/env/build_env.sh#L51

**Comment by casper-110368104** [comment]
TKS!
