### ISSUE TITLE
How to use your trained model directly?

### ISSUE THREAD

**Issue by JunZhan2000** [jctian98/e2e_lfmmi#7]
How to use your trained model directly, can you give an example? thank you very much

**Comment by jctian98** [comment]
Hi. To use the trained model directly, you can unzip the downloaded file in `exp/` and run:
```
bash nt.sh --stage 2 --tag <tag-of-exp> --mmi-weight 0.2 --word-ngram-weight 0.4
```

Before that, you may need to run `prepare.sh` to extract the features and train the LM.

**Comment by jctian98** [comment]
Please feel free to tell me if there is a problem :)
